-- ============================================================================
-- Hakustore — script SQL completo (schema + dati di sistema)
-- Da eseguire una sola volta su un database vuoto per allineare tutte le tabelle
-- allo stato attuale delle entity JPA (Categoria/Prodotto/VarianteProdotto,
-- Carrello/DettaglioCarrello/Coupon, Ordine/DettaglioOrdine, Utente/Indirizzo/Recensione).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) SCHEMA: creazione tabelle
-- ----------------------------------------------------------------------------

create table if not exists carrello (
    id_carrello integer generated by default as identity,
    id_coupon integer,
    id_utente integer not null unique,
    data_creazione timestamp(6) not null,
    primary key (id_carrello)
);

create table if not exists categoria (
    id_categoria integer generated by default as identity,
    nome varchar(100) not null unique,
    primary key (id_categoria)
);

create table if not exists coupon (
    id_coupon integer generated by default as identity,
    is_attivo boolean not null,
    valore numeric(10,2) not null,
    data_fine timestamp(6) not null,
    data_inizio timestamp(6) not null,
    codice varchar(50) not null unique,
    tipologia varchar(255) not null check ((tipologia in ('PERCENTUALE','FISSO'))),
    primary key (id_coupon)
);

create table if not exists dettaglio_carrello (
    id_carrello integer not null,
    id_dettaglio integer generated by default as identity,
    id_variante integer not null,
    quantita integer not null,
    primary key (id_dettaglio),
    constraint uk_carrello_variante unique (id_carrello, id_variante)
);

create table if not exists dettaglio_ordine (
    id_dettaglio integer generated by default as identity,
    id_ordine integer not null,
    id_variante integer not null,
    prezzo_unitario numeric(10,2) not null,
    quantita integer not null,
    primary key (id_dettaglio)
);

create table if not exists indirizzo (
    id_indirizzo integer generated by default as identity,
    id_utente integer not null,
    cap varchar(10) not null,
    citta varchar(50) not null,
    nazione varchar(50) not null,
    provincia varchar(50),
    via varchar(100) not null,
    primary key (id_indirizzo)
);

create table if not exists messaggi_sistema (
    lang varchar(4) not null,
    code varchar(50) not null,
    messagio varchar(255),
    primary key (lang, code)
);

create table if not exists ordine (
    id_ordine integer generated by default as identity,
    id_utente integer not null,
    totale_pagato numeric(10,2) not null,
    totale_prodotti numeric(10,2) not null,
    valore_sconto numeric(10,2) not null,
    data_ordine timestamp(6) not null,
    spedizione_cap varchar(10) not null,
    codice_coupon_usato varchar(50),
    metodo_pagamento varchar(50) not null,
    spedizione_citta varchar(50) not null,
    spedizione_nazione varchar(50) not null,
    spedizione_provincia varchar(50),
    spedizione_via varchar(100) not null,
    stato varchar(255) not null check ((stato in ('IN_ATTESA','ELABORATO','SPEDITO','ANNULLATO'))),
    stato_pagamento varchar(255) not null check ((stato_pagamento in ('DA_PAGARE','APPROVATO','FALLITO'))),
    primary key (id_ordine)
);

create table if not exists prodotto (
    id_categoria integer not null,
    id_prodotto integer generated by default as identity,
    marca varchar(80) not null,
    nome varchar(150) not null,
    descrizione TEXT,
    immagine varchar(255),
    data_creazione timestamp(6) not null,
    primary key (id_prodotto)
);

create table if not exists recensione (
    id_prodotto integer not null,
    id_recensione integer generated by default as identity,
    id_utente integer not null,
    voto integer not null,
    data_recensione timestamp(6) not null,
    titolo varchar(100),
    commento TEXT,
    primary key (id_recensione)
);

create table if not exists utente (
    id_utente integer generated by default as identity,
    telefono varchar(20),
    cognome varchar(50) not null,
    nome varchar(50) not null,
    email varchar(100) not null unique,
    password varchar(255) not null,
    ruolo varchar(255) not null check ((ruolo in ('CLIENTE','ADMIN'))),
    primary key (id_utente)
);

create table if not exists variante_prodotto (
    id_prodotto integer not null,
    id_variante integer generated by default as identity,
    prezzo numeric(10,2) not null,
    quantita_disponibile integer not null,
    colore varchar(50),
    formato varchar(50),
    gusto varchar(50),
    immagine varchar(255),
    data_rifornimento timestamp(6),
    primary key (id_variante)
);

-- ----------------------------------------------------------------------------
-- 2) SCHEMA: vincoli di chiave esterna
-- ----------------------------------------------------------------------------

alter table if exists carrello
   add constraint fk_carrello_coupon
   foreign key (id_coupon)
   references coupon;

alter table if exists carrello
   add constraint fk_carrello_utente
   foreign key (id_utente)
   references utente
   on delete cascade;

alter table if exists dettaglio_carrello
   add constraint fk_dettaglio_carrello_carrello
   foreign key (id_carrello)
   references carrello
   on delete cascade;

alter table if exists dettaglio_carrello
   add constraint fk_dettaglio_carrello_variante
   foreign key (id_variante)
   references variante_prodotto;

alter table if exists dettaglio_ordine
   add constraint fk_dettaglio_ordine_ordine
   foreign key (id_ordine)
   references ordine
   on delete cascade;

alter table if exists dettaglio_ordine
   add constraint fk_dettaglio_ordine_variante
   foreign key (id_variante)
   references variante_prodotto;

alter table if exists indirizzo
   add constraint fk_indirizzo_utente
   foreign key (id_utente)
   references utente
   on delete cascade;

alter table if exists ordine
   add constraint fk_ordine_utente
   foreign key (id_utente)
   references utente
   on delete cascade;

alter table if exists prodotto
   add constraint fk_prodotto_categoria
   foreign key (id_categoria)
   references categoria;

alter table if exists recensione
   add constraint fk_recensione_prodotto
   foreign key (id_prodotto)
   references prodotto
   on delete cascade;

alter table if exists recensione
   add constraint fk_recensione_utente
   foreign key (id_utente)
   references utente
   on delete cascade;

alter table if exists variante_prodotto
   add constraint fk_variante_prodotto
   foreign key (id_prodotto)
   references prodotto
   on delete cascade;

-- ----------------------------------------------------------------------------
-- 3) DATI: messaggi di sistema (i18n), un codice per ogni errore/regola di business
-- ----------------------------------------------------------------------------

INSERT INTO messaggi_sistema (lang, code, messagio) VALUES
('IT', 'auth.badcredentials', 'Email o password non validi.'),
('IT', 'auth.forbidden', 'Non hai i permessi per eseguire questa operazione.'),
('IT', 'auth.unauthorized', 'Devi effettuare il login per accedere a questa risorsa.'),
('IT', 'auth.no.email', 'Inserisci l''email.'),
('IT', 'auth.no.password', 'Inserisci la password.'),

('IT', 'utente.ntfnd', 'Utente non trovato.'),
('IT', 'utente.forbidden', 'Non puoi modificare i dati di un altro utente.'),
('IT', 'utente.email.exists', 'Esiste gia'' un utente con questa email.'),
('IT', 'utente.email.invalid', 'L''indirizzo email non e'' valido.'),
('IT', 'utente.no.id', 'ID utente mancante.'),
('IT', 'utente.no.nome', 'Inserisci il nome.'),
('IT', 'utente.no.cognome', 'Inserisci il cognome.'),
('IT', 'utente.no.email', 'Inserisci l''email.'),
('IT', 'utente.no.password', 'Inserisci la password.'),
('IT', 'utente.password.short', 'La password deve contenere almeno 8 caratteri.'),

('IT', 'indirizzo.ntfnd', 'Indirizzo non trovato.'),
('IT', 'indirizzo.forbidden', 'Non puoi modificare un indirizzo che non ti appartiene.'),
('IT', 'indirizzo.no.id', 'ID indirizzo mancante.'),
('IT', 'indirizzo.no.via', 'Inserisci la via.'),
('IT', 'indirizzo.no.citta', 'Inserisci la citta''.'),
('IT', 'indirizzo.no.cap', 'Inserisci il CAP.'),

('IT', 'categoria.ntfnd', 'Categoria non trovata.'),
('IT', 'categoria.nome.exist', 'Esiste gia'' una categoria con questo nome.'),
('IT', 'categoria.has.prodotti', 'Impossibile eliminare la categoria: sono presenti prodotti collegati.'),
('IT', 'categoria.no.id', 'ID categoria mancante.'),
('IT', 'categoria.no.nome', 'Inserisci il nome della categoria.'),

('IT', 'prodotto.ntfnd', 'Prodotto non trovato.'),
('IT', 'prodotto.exists', 'Esiste gia'' un prodotto con questo nome per questa marca.'),
('IT', 'prodotto.no.id', 'ID prodotto mancante.'),
('IT', 'prodotto.no.categoria', 'Seleziona la categoria del prodotto.'),
('IT', 'prodotto.no.nome', 'Inserisci il nome del prodotto.'),
('IT', 'prodotto.no.marca', 'Inserisci la marca del prodotto.'),

('IT', 'variante.ntfnd', 'Variante prodotto non trovata.'),
('IT', 'variante.exists', 'Esiste gia'' una variante con questi stessi attributi per questo prodotto.'),
('IT', 'variante.stock.insufficient', 'Quantita'' non disponibile in magazzino.'),
('IT', 'variante.no.id', 'ID variante mancante.'),
('IT', 'variante.no.prodotto', 'Seleziona il prodotto.'),
('IT', 'variante.no.prezzo', 'Inserisci il prezzo.'),
('IT', 'variante.prezzo.invalid', 'Il prezzo non puo'' essere negativo.'),
('IT', 'variante.quantita.invalid', 'La quantita'' disponibile non puo'' essere negativa.'),

('IT', 'recensione.ntfnd', 'Recensione non trovata.'),
('IT', 'recensione.forbidden', 'Non puoi modificare una recensione che non e'' tua.'),
('IT', 'recensione.no.id', 'ID recensione mancante.'),
('IT', 'recensione.no.prodotto', 'Seleziona il prodotto da recensire.'),
('IT', 'recensione.no.voto', 'Inserisci un voto.'),
('IT', 'recensione.voto.invalid', 'Il voto deve essere compreso tra 1 e 5.'),

('IT', 'coupon.ntfnd', 'Coupon non trovato.'),
('IT', 'coupon.codice.exist', 'Esiste gia'' un coupon con questo codice.'),
('IT', 'coupon.not.active', 'Il coupon non e'' attivo.'),
('IT', 'coupon.not.started', 'Il coupon non e'' ancora valido.'),
('IT', 'coupon.expired', 'Il coupon e'' scaduto.'),
('IT', 'coupon.dates.invalid', 'La data di fine deve essere successiva alla data di inizio.'),
('IT', 'coupon.already.used', 'Hai già utilizzato questo coupon in un ordine precedente.'),
('IT', 'coupon.no.id', 'ID coupon mancante.'),
('IT', 'coupon.no.codice', 'Inserisci il codice del coupon.'),
('IT', 'coupon.no.tipologia', 'Seleziona il tipo di coupon (percentuale o fisso).'),
('IT', 'coupon.no.valore', 'Inserisci il valore dello sconto.'),
('IT', 'coupon.valore.invalid', 'Il valore dello sconto deve essere maggiore di zero.'),
('IT', 'coupon.no.data.inizio', 'Inserisci la data di inizio validita''.'),
('IT', 'coupon.no.data.fine', 'Inserisci la data di fine validita''.'),

('IT', 'carrello.empty', 'Il carrello e'' vuoto.'),
('IT', 'carrello.no.variante', 'Seleziona una variante del prodotto.'),
('IT', 'carrello.no.quantita', 'Inserisci la quantita''.'),
('IT', 'carrello.quantita.invalid', 'La quantita'' deve essere almeno 1.'),
('IT', 'carrello.no.codice.coupon', 'Inserisci il codice del coupon.'),
('IT', 'dettaglio.ntfnd', 'Articolo del carrello non trovato.'),

('IT', 'ordine.ntfnd', 'Ordine non trovato.'),
('IT', 'ordine.forbidden', 'Non puoi visualizzare un ordine che non ti appartiene.'),
('IT', 'ordine.no.id', 'ID ordine mancante.'),
('IT', 'ordine.no.indirizzo', 'Seleziona l''indirizzo di spedizione.'),
('IT', 'ordine.no.metodo.pagamento', 'Seleziona il metodo di pagamento.'),

('IT', 'categoria.immagine.mancante', 'Seleziona un file immagine da caricare.'),
('IT', 'categoria.immagine.formato.invalido', 'Formato immagine non supportato (usa jpg, png, gif o webp).'),
('IT', 'categoria.immagine.errore.salvataggio', 'Errore durante il salvataggio dell''immagine.'),
('IT', 'variante.immagine.mancante', 'Seleziona un file immagine da caricare.'),
('IT', 'variante.immagine.formato.invalido', 'Formato immagine non supportato (usa jpg, png, gif o webp).'),
('IT', 'variante.immagine.errore.salvataggio', 'Errore durante il salvataggio dell''immagine.'),
('IT', 'logo.mancante', 'Seleziona un file immagine da caricare.'),
('IT', 'logo.formato.invalido', 'Formato immagine non supportato (usa jpg, png, gif, webp o svg).'),
('IT', 'logo.errore.salvataggio', 'Errore durante il salvataggio del logo.'),
('IT', 'upload.tipo.invalido', 'Tipo di upload non riconosciuto.')
ON CONFLICT (lang, code) DO UPDATE SET messagio = EXCLUDED.messagio;
