create table if not exists carrello (
    id_carrello integer generated by default as identity,
    id_coupon integer,
    id_utente integer not null unique,
    data_creazione timestamp(6) not null,
    primary key (id_carrello)
);

create table if not exists categoria (
    id_categoria integer generated by default as identity,
    nome varchar(100) not null unique,
    immagine varchar(255),
    primary key (id_categoria)
);

-- Esegui questo se la tabella categoria esiste gia' senza la colonna immagine:
-- ALTER TABLE categoria ADD COLUMN IF NOT EXISTS immagine varchar(255);

create table if not exists coupon (
    id_coupon integer generated by default as identity,
    is_attivo boolean not null,
    valore numeric(10,2) not null,
    data_fine timestamp(6) not null,
    data_inizio timestamp(6) not null,
    codice varchar(50) not null unique,
    tipologia varchar(255) not null check ((tipologia in ('PERCENTUALE','FISSO'))),
    primary key (id_coupon)
);

create table if not exists dettaglio_carrello (
    id_carrello integer not null,
    id_dettaglio integer generated by default as identity,
    id_variante integer not null,
    quantita integer not null,
    primary key (id_dettaglio),
    constraint uk_carrello_variante unique (id_carrello, id_variante)
);

create table if not exists dettaglio_ordine (
    id_dettaglio integer generated by default as identity,
    id_ordine integer not null,
    id_variante integer not null,
    prezzo_unitario numeric(10,2) not null,
    quantita integer not null,
    primary key (id_dettaglio)
);

create table if not exists indirizzo (
    id_indirizzo integer generated by default as identity,
    id_utente integer not null,
    cap varchar(10) not null,
    citta varchar(50) not null,
    nazione varchar(50) not null,
    provincia varchar(50),
    via varchar(100) not null,
    primary key (id_indirizzo)
);

create table if not exists messaggi_sistema (
    lang varchar(4) not null,
    code varchar(50) not null,
    messagio varchar(255),
    primary key (lang, code)
);

create table if not exists ordine (
    id_ordine integer generated by default as identity,
    id_utente integer not null,
    totale_pagato numeric(10,2) not null,
    totale_prodotti numeric(10,2) not null,
    valore_sconto numeric(10,2) not null,
    data_ordine timestamp(6) not null,
    spedizione_cap varchar(10) not null,
    codice_coupon_usato varchar(50),
    metodo_pagamento varchar(50) not null,
    spedizione_citta varchar(50) not null,
    spedizione_nazione varchar(50) not null,
    spedizione_provincia varchar(50),
    spedizione_via varchar(100) not null,
    stato varchar(255) not null check ((stato in ('IN_ATTESA','ELABORATO','SPEDITO','ANNULLATO'))),
    stato_pagamento varchar(255) not null check ((stato_pagamento in ('DA_PAGARE','APPROVATO','FALLITO'))),
    primary key (id_ordine)
);

create table if not exists password_reset_token (
    id_token bigint generated by default as identity,
    id_utente integer not null,
    token_hash varchar(64) not null unique,
    data_scadenza timestamp(6) not null,
    data_utilizzo timestamp(6),
    primary key (id_token)
);

create table if not exists prodotto (
    id_categoria integer not null,
    id_prodotto integer generated by default as identity,
    marca varchar(80) not null,
    nome varchar(150) not null,
    descrizione TEXT,
    immagine varchar(255),
    data_creazione timestamp(6) not null,
    primary key (id_prodotto)
);

-- Esegui questo se la tabella prodotto esiste gia' senza la colonna immagine:
-- ALTER TABLE prodotto ADD COLUMN IF NOT EXISTS immagine varchar(255);

-- Esegui questo se la tabella prodotto esiste gia' senza la colonna data_creazione
-- (il default CURRENT_TIMESTAMP valorizza subito i prodotti gia' esistenti, cosi' non restano null):
-- ALTER TABLE prodotto ADD COLUMN IF NOT EXISTS data_creazione timestamp(6) DEFAULT CURRENT_TIMESTAMP NOT NULL;

create table if not exists recensione (
    id_prodotto integer not null,
    id_recensione integer generated by default as identity,
    id_utente integer not null,
    voto integer not null,
    data_recensione timestamp(6) not null,
    titolo varchar(100),
    commento TEXT,
    primary key (id_recensione)
);

create table if not exists utente (
    id_utente integer generated by default as identity,
    telefono varchar(20),
    cognome varchar(50) not null,
    nome varchar(50) not null,
    email varchar(100) not null unique,
    password varchar(255) not null,
    ruolo varchar(255) not null check ((ruolo in ('CLIENTE','ADMIN'))),
    primary key (id_utente)
);

create table if not exists variante_prodotto (
    id_prodotto integer not null,
    id_variante integer generated by default as identity,
    prezzo numeric(10,2) not null,
    quantita_disponibile integer not null,
    colore varchar(50),
    formato varchar(50),
    gusto varchar(50),
    immagine varchar(255),
    data_rifornimento timestamp(6),
    primary key (id_variante)
);

-- Esegui questo se la tabella variante_prodotto esiste gia' senza la colonna immagine:
-- ALTER TABLE variante_prodotto ADD COLUMN IF NOT EXISTS immagine varchar(255);

-- Esegui questo se la tabella variante_prodotto esiste gia' senza la colonna data_rifornimento:
-- ALTER TABLE variante_prodotto ADD COLUMN IF NOT EXISTS data_rifornimento timestamp(6);

alter table if exists carrello
   add constraint fk_carrello_coupon
   foreign key (id_coupon)
   references coupon;

alter table if exists carrello
   add constraint fk_carrello_utente
   foreign key (id_utente)
   references utente
   on delete cascade;

alter table if exists dettaglio_carrello
   add constraint fk_dettaglio_carrello_carrello
   foreign key (id_carrello)
   references carrello
   on delete cascade;

alter table if exists dettaglio_carrello
   add constraint fk_dettaglio_carrello_variante
   foreign key (id_variante)
   references variante_prodotto;

alter table if exists dettaglio_ordine
   add constraint fk_dettaglio_ordine_ordine
   foreign key (id_ordine)
   references ordine
   on delete cascade;

alter table if exists dettaglio_ordine
   add constraint fk_dettaglio_ordine_variante
   foreign key (id_variante)
   references variante_prodotto;

alter table if exists indirizzo
   add constraint fk_indirizzo_utente
   foreign key (id_utente)
   references utente
   on delete cascade;

alter table if exists ordine
   add constraint fk_ordine_utente
   foreign key (id_utente)
   references utente
   on delete cascade;

alter table if exists password_reset_token
   add constraint fk_password_reset_utente
   foreign key (id_utente)
   references utente
   on delete cascade;

alter table if exists prodotto
   add constraint fk_prodotto_categoria
   foreign key (id_categoria)
   references categoria;

alter table if exists recensione
   add constraint fk_recensione_prodotto
   foreign key (id_prodotto)
   references prodotto
   on delete cascade;

alter table if exists recensione
   add constraint fk_recensione_utente
   foreign key (id_utente)
   references utente
   on delete cascade;

alter table if exists variante_prodotto
   add constraint fk_variante_prodotto
   foreign key (id_prodotto)
   references prodotto
   on delete cascade;
